### ISSUE TITLE
KeyError: 'obj_9' after resetting target

### ISSUE THREAD

**Issue by Kami-code** [NVlabs/SceneCollisionNet#4]
Hi @mjd3 . Thanks for providing us such an excellent work. Recenly, I am trying to reproduce your work. But I faced an unexpected error when I execute the following command:
`python tools/rollout_policy.py --self-coll-nn weights/self_coll_nn --scene-coll-nn weights/scene_coll_nn --control-frequency 1`

> MPPIPolicy INFO     found lift plan
MPPIPolicy DEBUG    index = 1, lift_plan = 20
MPPIPolicy DEBUG    index = 4, lift_plan = 20
MPPIPolicy DEBUG    index = 18, lift_plan = 20
MPPIPolicy DEBUG    index = 19, lift_plan = 20
RobotEnvironment INFO     =================== RESET TARGET ===============
Traceback (most recent call last):
  File "tools/rollout_policy.py", line 99, in <module>
    rollout(args)
  File "tools/rollout_policy.py", line 39, in rollout
    next_o, info = env.step(a)
  File "/home/flexiv/Desktop/projects/SceneCollisionNet/scenecollisionnet/policy/robot_environment.py", line 477, in step
    self.scene_manager.objs[self._target_name]["grasps"]
KeyError: 'obj_9'

This problem sometimes happens when I execute the command. Sometimes happens when I init the environment at first, sometime happens when the code tries to reset the target. Also the missing key index varies. Thanks for your help!

**Comment by Kami-code** [comment]
I found that when loading an object over max_attempts [https://github.com/NVlabs/SceneCollisionNet/blob/f27cc6305e1a9af5b9878526a13c4fa31b1a2b7e/scenecollisionnet/scene.py#L165](https://github.com/NVlabs/SceneCollisionNet/blob/f27cc6305e1a9af5b9878526a13c4fa31b1a2b7e/scenecollisionnet/scene.py#L165) will cause a key to be deleted but will be referred at [https://github.com/NVlabs/SceneCollisionNet/blob/f27cc6305e1a9af5b9878526a13c4fa31b1a2b7e/scenecollisionnet/policy/robot_environment.py#L1041](https://github.com/NVlabs/SceneCollisionNet/blob/f27cc6305e1a9af5b9878526a13c4fa31b1a2b7e/scenecollisionnet/policy/robot_environment.py#L1041)
